#
# Description: This playbook runs each role required to setup the server to desired state.
# Example: ansible-playbook -i inventory server_config.yaml --ask-become-pass
#
---
- name: Home server configuration setup
  hosts: all
#  become: true

  tasks:
  # step 1, configure .ssh dir of target user
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "{{ target_user_home }}/.ssh"
        state: directory
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: "0700"

    - name: Copy ssh private key to {{ target_user }}
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ target_user_home }}/.ssh/"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0600'
      with_items:
        - authorized_keys
        - id_rsa
        - id_rsa.pub

  # step 2 install applications needed
    - name: Install required packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items:
        - docker
        - docker-compose
        - git

  # step 3 config
    - name: Ensure gitconfig is configured
      ansible.builtin.copy:
        src: "gitconfig"
        dest: "{{ target_user_home }}/.gitconfig"
        owner: "{{ target_user }}"
        group: "{{ target_user }}"
        mode: '0644'

  # step 3 make sure user has access to docker group
    - name: Append docker group to {{ target_user }}
      ansible.builtin.user:
        name: "{{ target_user }}"
        groups: docker
        append: true
